# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astro/messaging/v1/audio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'astro/messaging/v1/audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61stro/messaging/v1/audio.proto\x12\x12\x61stro.messaging.v1\"\xbb\x01\n\x11\x41udioStreamConfig\x12\x33\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32!.astro.messaging.v1.AudioEncoding\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t\x12\x0f\n\x07user_id\x18\x07 \x01(\t\":\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08sequence\x18\x02 \x01(\x03\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"\x89\x01\n\x12\x41udioStreamRequest\x12\x37\n\x06\x63onfig\x18\x01 \x01(\x0b\x32%.astro.messaging.v1.AudioStreamConfigH\x00\x12/\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x1e.astro.messaging.v1.AudioChunkH\x00\x42\t\n\x07request*\x8b\x01\n\rAudioEncoding\x12\x1e\n\x1a\x41UDIO_ENCODING_UNSPECIFIED\x10\x00\x12\x0c\n\x08LINEAR16\x10\x01\x12\t\n\x05MULAW\x10\x02\x12\x08\n\x04OPUS\x10\x03\x12\x07\n\x03MP3\x10\x04\x12\r\n\tWEBM_OPUS\x10\x05\x12\x0c\n\x08OGG_OPUS\x10\x06\x12\x08\n\x04\x46LAC\x10\x07\x12\x07\n\x03\x41\x41\x43\x10\x08\x42\x33Z1github.com/postman/astro/messaging/v1;messagingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astro.messaging.v1.audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/postman/astro/messaging/v1;messagingv1'
  _globals['_AUDIOENCODING']._serialized_start=445
  _globals['_AUDIOENCODING']._serialized_end=584
  _globals['_AUDIOSTREAMCONFIG']._serialized_start=55
  _globals['_AUDIOSTREAMCONFIG']._serialized_end=242
  _globals['_AUDIOCHUNK']._serialized_start=244
  _globals['_AUDIOCHUNK']._serialized_end=302
  _globals['_AUDIOSTREAMREQUEST']._serialized_start=305
  _globals['_AUDIOSTREAMREQUEST']._serialized_end=442
# @@protoc_insertion_point(module_scope)
