# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astro/messaging/v1/renderable.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'astro/messaging/v1/renderable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#astro/messaging/v1/renderable.proto\x12\x12\x61stro.messaging.v1\"\xd4\x01\n\nRenderable\x12\n\n\x02id\x18\x01 \x01(\t\x12,\n\x04kind\x18\x02 \x01(\x0e\x32\x1e.astro.messaging.v1.RenderKind\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x18\n\x10\x64\x61ta_schema_json\x18\x04 \x01(\t\x12\x12\n\nvalue_json\x18\x05 \x01(\t\x12=\n\x0f\x61llowed_actions\x18\x06 \x03(\x0e\x32$.astro.messaging.v1.RenderableAction\x12\x0e\n\x06intent\x18\x07 \x01(\t\"z\n\x12RenderableResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x34\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32$.astro.messaging.v1.RenderableAction\x12\x14\n\x0c\x63ontent_json\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t*?\n\nRenderKind\x12\x1b\n\x17RENDER_KIND_UNSPECIFIED\x10\x00\x12\x14\n\x10RENDER_KIND_FORM\x10\x01*\xd2\x01\n\x10RenderableAction\x12!\n\x1dRENDERABLE_ACTION_UNSPECIFIED\x10\x00\x12\x1c\n\x18RENDERABLE_ACTION_SUBMIT\x10\x01\x12\x1d\n\x19RENDERABLE_ACTION_DECLINE\x10\x02\x12\x1c\n\x18RENDERABLE_ACTION_CANCEL\x10\x03\x12\x1d\n\x19RENDERABLE_ACTION_RESPOND\x10\x04\x12!\n\x1dRENDERABLE_ACTION_UNSUPPORTED\x10\x05\x42\x33Z1github.com/postman/astro/messaging/v1;messagingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astro.messaging.v1.renderable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/postman/astro/messaging/v1;messagingv1'
  _globals['_RENDERKIND']._serialized_start=398
  _globals['_RENDERKIND']._serialized_end=461
  _globals['_RENDERABLEACTION']._serialized_start=464
  _globals['_RENDERABLEACTION']._serialized_end=674
  _globals['_RENDERABLE']._serialized_start=60
  _globals['_RENDERABLE']._serialized_end=272
  _globals['_RENDERABLERESPONSE']._serialized_start=274
  _globals['_RENDERABLERESPONSE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
