# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audio_pb2 as astro_dot_messaging_dot_v1_dot_audio__pb2
from . import message_pb2 as astro_dot_messaging_dot_v1_dot_message__pb2
from . import response_pb2 as astro_dot_messaging_dot_v1_dot_response__pb2
from . import service_pb2 as astro_dot_messaging_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in astro/messaging/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentMessagingStub(object):
    """Main gRPC service for agent messaging
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessConversation = channel.stream_stream(
                '/astro.messaging.v1.AgentMessaging/ProcessConversation',
                request_serializer=astro_dot_messaging_dot_v1_dot_service__pb2.ConversationRequest.SerializeToString,
                response_deserializer=astro_dot_messaging_dot_v1_dot_response__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.ProcessMessage = channel.unary_stream(
                '/astro.messaging.v1.AgentMessaging/ProcessMessage',
                request_serializer=astro_dot_messaging_dot_v1_dot_message__pb2.Message.SerializeToString,
                response_deserializer=astro_dot_messaging_dot_v1_dot_response__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.GetThreadHistory = channel.unary_unary(
                '/astro.messaging.v1.AgentMessaging/GetThreadHistory',
                request_serializer=astro_dot_messaging_dot_v1_dot_response__pb2.ThreadHistoryRequest.SerializeToString,
                response_deserializer=astro_dot_messaging_dot_v1_dot_response__pb2.ThreadHistoryResponse.FromString,
                _registered_method=True)
        self.GetConversationMetadata = channel.unary_unary(
                '/astro.messaging.v1.AgentMessaging/GetConversationMetadata',
                request_serializer=astro_dot_messaging_dot_v1_dot_service__pb2.ConversationMetadataRequest.SerializeToString,
                response_deserializer=astro_dot_messaging_dot_v1_dot_service__pb2.ConversationMetadataResponse.FromString,
                _registered_method=True)
        self.ProcessAudioStream = channel.stream_stream(
                '/astro.messaging.v1.AgentMessaging/ProcessAudioStream',
                request_serializer=astro_dot_messaging_dot_v1_dot_audio__pb2.AudioStreamRequest.SerializeToString,
                response_deserializer=astro_dot_messaging_dot_v1_dot_response__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/astro.messaging.v1.AgentMessaging/HealthCheck',
                request_serializer=astro_dot_messaging_dot_v1_dot_service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=astro_dot_messaging_dot_v1_dot_service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AgentMessagingServicer(object):
    """Main gRPC service for agent messaging
    """

    def ProcessConversation(self, request_iterator, context):
        """Bidirectional streaming for real-time AI conversations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessMessage(self, request, context):
        """Server streaming for simple request/response with streaming reply
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThreadHistory(self, request, context):
        """Get current thread history from platform (handles edits/deletes)
        Agent calls this to hydrate accurate thread state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversationMetadata(self, request, context):
        """Optional: Query cache for conversation metadata (not full history)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAudioStream(self, request_iterator, context):
        """Audio: client streams raw audio, server responds with text
        First message MUST be AudioStreamConfig, rest are AudioChunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentMessagingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessConversation': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessConversation,
                    request_deserializer=astro_dot_messaging_dot_v1_dot_service__pb2.ConversationRequest.FromString,
                    response_serializer=astro_dot_messaging_dot_v1_dot_response__pb2.AgentResponse.SerializeToString,
            ),
            'ProcessMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessMessage,
                    request_deserializer=astro_dot_messaging_dot_v1_dot_message__pb2.Message.FromString,
                    response_serializer=astro_dot_messaging_dot_v1_dot_response__pb2.AgentResponse.SerializeToString,
            ),
            'GetThreadHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThreadHistory,
                    request_deserializer=astro_dot_messaging_dot_v1_dot_response__pb2.ThreadHistoryRequest.FromString,
                    response_serializer=astro_dot_messaging_dot_v1_dot_response__pb2.ThreadHistoryResponse.SerializeToString,
            ),
            'GetConversationMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversationMetadata,
                    request_deserializer=astro_dot_messaging_dot_v1_dot_service__pb2.ConversationMetadataRequest.FromString,
                    response_serializer=astro_dot_messaging_dot_v1_dot_service__pb2.ConversationMetadataResponse.SerializeToString,
            ),
            'ProcessAudioStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessAudioStream,
                    request_deserializer=astro_dot_messaging_dot_v1_dot_audio__pb2.AudioStreamRequest.FromString,
                    response_serializer=astro_dot_messaging_dot_v1_dot_response__pb2.AgentResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=astro_dot_messaging_dot_v1_dot_service__pb2.HealthCheckRequest.FromString,
                    response_serializer=astro_dot_messaging_dot_v1_dot_service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'astro.messaging.v1.AgentMessaging', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('astro.messaging.v1.AgentMessaging', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentMessaging(object):
    """Main gRPC service for agent messaging
    """

    @staticmethod
    def ProcessConversation(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/astro.messaging.v1.AgentMessaging/ProcessConversation',
            astro_dot_messaging_dot_v1_dot_service__pb2.ConversationRequest.SerializeToString,
            astro_dot_messaging_dot_v1_dot_response__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astro.messaging.v1.AgentMessaging/ProcessMessage',
            astro_dot_messaging_dot_v1_dot_message__pb2.Message.SerializeToString,
            astro_dot_messaging_dot_v1_dot_response__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThreadHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astro.messaging.v1.AgentMessaging/GetThreadHistory',
            astro_dot_messaging_dot_v1_dot_response__pb2.ThreadHistoryRequest.SerializeToString,
            astro_dot_messaging_dot_v1_dot_response__pb2.ThreadHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversationMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astro.messaging.v1.AgentMessaging/GetConversationMetadata',
            astro_dot_messaging_dot_v1_dot_service__pb2.ConversationMetadataRequest.SerializeToString,
            astro_dot_messaging_dot_v1_dot_service__pb2.ConversationMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAudioStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/astro.messaging.v1.AgentMessaging/ProcessAudioStream',
            astro_dot_messaging_dot_v1_dot_audio__pb2.AudioStreamRequest.SerializeToString,
            astro_dot_messaging_dot_v1_dot_response__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astro.messaging.v1.AgentMessaging/HealthCheck',
            astro_dot_messaging_dot_v1_dot_service__pb2.HealthCheckRequest.SerializeToString,
            astro_dot_messaging_dot_v1_dot_service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
