# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astro/messaging/v1/skill.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'astro/messaging/v1/skill.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61stro/messaging/v1/skill.proto\x12\x12\x61stro.messaging.v1\"D\n\x05Skill\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x18\n\x10long_description\x18\x03 \x01(\t\"4\n\x08\x41\x64\x64Skill\x12(\n\x05skill\x18\x01 \x01(\x0b\x32\x19.astro.messaging.v1.Skill\"\x1b\n\x0bRemoveSkill\x12\x0c\n\x04name\x18\x01 \x01(\t\"3\n\x0fSkillInvocation\x12\x12\n\nskill_name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\tB3Z1github.com/postman/astro/messaging/v1;messagingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astro.messaging.v1.skill_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/postman/astro/messaging/v1;messagingv1'
  _globals['_SKILL']._serialized_start=54
  _globals['_SKILL']._serialized_end=122
  _globals['_ADDSKILL']._serialized_start=124
  _globals['_ADDSKILL']._serialized_end=176
  _globals['_REMOVESKILL']._serialized_start=178
  _globals['_REMOVESKILL']._serialized_end=205
  _globals['_SKILLINVOCATION']._serialized_start=207
  _globals['_SKILLINVOCATION']._serialized_end=258
# @@protoc_insertion_point(module_scope)
