# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astro/messaging/v1/trace.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'astro/messaging/v1/trace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61stro/messaging/v1/trace.proto\x12\x12\x61stro.messaging.v1\"7\n\x0cTraceContext\x12\x13\n\x0btraceparent\x18\x01 \x01(\t\x12\x12\n\ntracestate\x18\x02 \x01(\tB3Z1github.com/postman/astro/messaging/v1;messagingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astro.messaging.v1.trace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/postman/astro/messaging/v1;messagingv1'
  _globals['_TRACECONTEXT']._serialized_start=54
  _globals['_TRACECONTEXT']._serialized_end=109
# @@protoc_insertion_point(module_scope)
